version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: library-deploy/Dockerfile-backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ..
      dockerfile: library-deploy/Dockerfile-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
