FROM python:3.12-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY library-deploy/backend/Pipfile /app/
COPY library-deploy/backend/Pipfile.lock /app/

RUN pip install --upgrade pip
RUN pip install pipenv
RUN pipenv install --system --deploy

COPY library-deploy/backend /app

RUN chmod +x /app/docker_entrypoints/run_backend.sh

EXPOSE 8000

CMD ["/bin/bash", "/app/docker_entrypoints/run_backend.sh"]