FROM python:3.12-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY ../backend/Pipfile /app/
COPY ../backend/Pipfile.lock /app/

RUN pip install --upgrade pip
RUN pip install pipenv
RUN pipenv install --system --deploy

COPY ../backend /app

RUN chmod +x /app/docker_entrypoints/run_backend.sh

EXPOSE 8000

ENTRYPOINT [ "/app/docker_entrypoints/run_backend.sh" ]
